version: '3'

services:

  pydag:
      build: ./pyDag/
      container_name: pydag
      depends_on:
        - redis
      networks:
        - redis
      volumes:          
          - ./pyDag/app/logs/:/pyDag/app/logs/:z    

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
    networks:
      - redis       

networks:
  redis:
    driver: bridge

